export type EntityConfig = {
  key: string;
  path: string; // admin API path suffix
  label: string;
  icon: string;
  columns: { key: string; label: string; render?: (v: any, row: any) => any }[];
  searchFields: string[];
  filters?: { key: string; label: string; options: string[] }[];
  editableFields?: { key: string; label: string; type?: string; options?: string[] }[];
  deletable?: boolean;
};

const cols = {
  idShort: (v: string) => (v ? v.slice(0, 8) + '…' : '-'),
};

export const ENTITIES: Record<string, EntityConfig> = {
  users: {
    key: 'users',
    path: 'users',
    label: 'Users',
    icon: '◐',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'phone', label: 'Phone', render: (v) => <span className="kbd">{v}</span> },
      { key: 'email', label: 'Email' },
      { key: 'governorate', label: 'Gov' },
      { key: 'city', label: 'City' },
      { key: 'createdAt', label: 'Created', render: (v, r) => new Date(v || r.created_at || '').toLocaleDateString() },
    ],
    searchFields: ['name', 'phone', 'email', 'governorate'],
    editableFields: [
      { key: 'name', label: 'Name' },
      { key: 'email', label: 'Email' },
      { key: 'governorate', label: 'Governorate' },
      { key: 'city', label: 'City' },
      { key: 'region', label: 'Region' },
      { key: 'placeType', label: 'Place Type' },
    ],
    deletable: true,
  },
  technicians: {
    key: 'technicians',
    path: 'technicians',
    label: 'Technicians',
    icon: '⬣',
    columns: [
      { key: 'fullName', label: 'Name', render: (v, r) => v || r.full_name },
      { key: 'phone', label: 'Phone', render: (v) => <span className="kbd">{v}</span> },
      { key: 'specialty', label: 'Specialty' },
      { key: 'governorate', label: 'Gov' },
      { key: 'rating', label: 'Rating' },
      { key: 'walletBalance', label: 'Wallet', render: (v, r) => (v ?? r.wallet_balance ?? 0) + ' EGP' },
      { key: 'is_verified', label: 'Verified', render: (v, r) => (v ?? r.isVerified ? '✓' : '—') },
    ],
    searchFields: ['fullName', 'phone', 'specialty', 'governorate'],
    editableFields: [
      { key: 'fullName', label: 'Full Name' },
      { key: 'specialty', label: 'Specialty' },
      { key: 'governorate', label: 'Governorate' },
      { key: 'area', label: 'Area' },
      { key: 'is_verified', label: 'Verified', type: 'select', options: ['true', 'false'] },
      { key: 'walletBalance', label: 'Wallet Balance', type: 'number' },
      { key: 'rating', label: 'Rating', type: 'number' },
    ],
    deletable: true,
  },
  requests: {
    key: 'requests',
    path: 'service-requests',
    label: 'Service Requests',
    icon: '⧉',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'serviceType', label: 'Service', render: (v, r) => v || r.service_type },
      { key: 'status', label: 'Status' },
      { key: 'budget', label: 'Budget' },
      { key: 'userGovernorate', label: 'Gov', render: (v, r) => v || r.user_governorate },
      { key: 'createdAt', label: 'Created', render: (v, r) => new Date(v || r.created_at || '').toLocaleDateString() },
    ],
    searchFields: ['title', 'description', 'status', 'serviceType'],
    filters: [{ key: 'status', label: 'Status', options: ['pending', 'offer_submitted', 'accepted', 'in_progress', 'completed', 'paid', 'cancelled'] }],
    editableFields: [
      { key: 'title', label: 'Title' },
      { key: 'description', label: 'Description', type: 'textarea' },
      { key: 'budget', label: 'Budget' },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'offer_submitted', 'accepted', 'in_progress', 'completed', 'paid', 'cancelled', 'rejected'] },
      { key: 'isPaid', label: 'Is Paid', type: 'select', options: ['true', 'false'] },
    ],
    deletable: true,
  },
  offers: {
    key: 'offers',
    path: 'offers',
    label: 'Offers',
    icon: '₿',
    columns: [
      { key: 'request_id', label: 'Request', render: (v, r) => cols.idShort(v || r.requestId) },
      { key: 'technician_id', label: 'Tech', render: (v) => <span className="kbd">{v?.slice(0, 10)}</span> },
      { key: 'price', label: 'Price', render: (v) => v + ' EGP' },
      { key: 'status', label: 'Status' },
      { key: 'createdAt', label: 'Created', render: (v, r) => new Date(v || r.created_at || '').toLocaleDateString() },
    ],
    searchFields: ['status', 'technician_id'],
    filters: [{ key: 'status', label: 'Status', options: ['pending', 'accepted', 'rejected', 'expired'] }],
    editableFields: [
      { key: 'price', label: 'Price', type: 'number' },
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'accepted', 'rejected', 'expired'] },
      { key: 'message', label: 'Message', type: 'textarea' },
    ],
    deletable: true,
  },
  payments: {
    key: 'payments',
    path: 'payment-logs',
    label: 'Payment Logs',
    icon: '₹',
    columns: [
      { key: 'user_id', label: 'User', render: (v, r) => cols.idShort(v || r.userId) },
      { key: 'amount', label: 'Amount', render: (v) => v + ' EGP' },
      { key: 'payment_method', label: 'Method', render: (v, r) => v || r.paymentMethod },
      { key: 'status', label: 'Status' },
      { key: 'createdAt', label: 'Date', render: (v, r) => new Date(v || r.created_at || '').toLocaleDateString() },
    ],
    searchFields: ['status', 'payment_method'],
    deletable: false,
  },
  transactions: {
    key: 'transactions',
    path: 'transactions',
    label: 'Transactions',
    icon: '⇄',
    columns: [
      { key: 'technician_id', label: 'Tech', render: (v) => <span className="kbd">{v?.slice(0, 10)}</span> },
      { key: 'amount', label: 'Amount' },
      { key: 'type', label: 'Type' },
      { key: 'created_at', label: 'Date', render: (v) => new Date(v || '').toLocaleDateString() },
    ],
    searchFields: ['technician_id', 'type'],
    deletable: false,
  },
  promos: {
    key: 'promos',
    path: 'promo-codes',
    label: 'Promo Codes',
    icon: '🏷',
    columns: [
      { key: 'code', label: 'Code', render: (v) => <span className="kbd">{v}</span> },
      { key: 'discount_type', label: 'Type' },
      { key: 'discount_value', label: 'Value' },
      { key: 'max_uses', label: 'Max' },
      { key: 'used_count', label: 'Used' },
      { key: 'is_active', label: 'Active', render: (v) => (v ? '✓' : '—') },
    ],
    searchFields: ['code'],
    editableFields: [
      { key: 'code', label: 'Code' },
      { key: 'discount_type', label: 'Discount Type', type: 'select', options: ['percentage', 'fixed'] },
      { key: 'discount_value', label: 'Discount Value', type: 'number' },
      { key: 'max_uses', label: 'Max Uses', type: 'number' },
      { key: 'is_active', label: 'Active', type: 'select', options: ['true', 'false'] },
    ],
    deletable: true,
  },
  posts: {
    key: 'posts',
    path: 'posts',
    label: 'Community Posts',
    icon: '▭',
    columns: [
      { key: 'title', label: 'Title' },
      { key: 'author_name', label: 'Author', render: (v, r) => v || r.authorName },
      { key: 'category', label: 'Category' },
      { key: 'likes', label: 'Likes' },
      { key: 'createdAt', label: 'Date', render: (v, r) => new Date(v || r.created_at || '').toLocaleDateString() },
    ],
    searchFields: ['title', 'content', 'author_name', 'category'],
    editableFields: [
      { key: 'title', label: 'Title' },
      { key: 'content', label: 'Content', type: 'textarea' },
      { key: 'category', label: 'Category' },
    ],
    deletable: true,
  },
  tickets: {
    key: 'tickets',
    path: 'support-tickets',
    label: 'Support Tickets',
    icon: '☎',
    columns: [
      { key: 'subject', label: 'Subject' },
      { key: 'user_id', label: 'User', render: (v) => cols.idShort(v) },
      { key: 'status', label: 'Status' },
      { key: 'priority', label: 'Priority' },
      { key: 'createdAt', label: 'Date', render: (v, r) => new Date(v || r.created_at || '').toLocaleDateString() },
    ],
    searchFields: ['subject', 'description', 'status'],
    filters: [{ key: 'status', label: 'Status', options: ['open', 'in_progress', 'resolved', 'closed'] }],
    editableFields: [
      { key: 'status', label: 'Status', type: 'select', options: ['open', 'in_progress', 'resolved', 'closed'] },
      { key: 'priority', label: 'Priority', type: 'select', options: ['low', 'medium', 'high', 'urgent'] },
      { key: 'adminReply', label: 'Admin Reply', type: 'textarea' },
    ],
    deletable: true,
  },
  reviews: {
    key: 'reviews',
    path: 'reviews',
    label: 'Reviews',
    icon: '★',
    columns: [
      { key: 'technician_id', label: 'Tech', render: (v) => <span className="kbd">{v?.slice(0, 10)}</span> },
      { key: 'rating', label: 'Rating' },
      { key: 'comment', label: 'Comment', render: (v) => (v || '').slice(0, 40) },
      { key: 'createdAt', label: 'Date', render: (v, r) => new Date(v || r.created_at || '').toLocaleDateString() },
    ],
    searchFields: ['comment', 'technician_id'],
    editableFields: [
      { key: 'rating', label: 'Rating', type: 'select', options: ['1', '2', '3', '4', '5'] },
      { key: 'comment', label: 'Comment', type: 'textarea' },
    ],
    deletable: true,
  },
  appointments: {
    key: 'appointments',
    path: 'appointments',
    label: 'Appointments',
    icon: '◰',
    columns: [
      { key: 'client_id', label: 'Client', render: (v) => cols.idShort(v) },
      { key: 'technician_id', label: 'Tech', render: (v) => <span className="kbd">{v?.slice(0, 10)}</span> },
      { key: 'service_type', label: 'Service' },
      { key: 'status', label: 'Status' },
      { key: 'appointment_date', label: 'Date' },
    ],
    searchFields: ['service_type', 'status'],
    filters: [{ key: 'status', label: 'Status', options: ['pending', 'scheduled', 'confirmed', 'in_progress', 'completed', 'cancelled'] }],
    editableFields: [
      { key: 'status', label: 'Status', type: 'select', options: ['pending', 'scheduled', 'confirmed', 'in_progress', 'completed', 'cancelled'] },
      { key: 'price', label: 'Price', type: 'number' },
      { key: 'notes', label: 'Notes', type: 'textarea' },
    ],
    deletable: true,
  },
  verifications: {
    key: 'verifications',
    path: 'verifications',
    label: 'Verifications',
    icon: '✓',
    columns: [
      { key: 'name', label: 'Name' },
      { key: 'phone', label: 'Phone', render: (v) => <span className="kbd">{v}</span> },
      { key: 'governorate', label: 'Gov' },
      { key: 'status', label: 'Status' },
      { key: 'created_at', label: 'Date', render: (v) => new Date(v || '').toLocaleDateString() },
    ],
    searchFields: ['name', 'phone', 'governorate', 'status'],
    filters: [{ key: 'status', label: 'Status', options: ['pending', 'approved', 'rejected'] }],
    editableFields: [{ key: 'status', label: 'Status', type: 'select', options: ['pending', 'approved', 'rejected'] }],
    deletable: false,
  },
  notifications: {
    key: 'notifications',
    path: 'notifications',
    label: 'Notifications',
    icon: '🔔',
    columns: [
      { key: 'user_id', label: 'User', render: (v) => cols.idShort(v) },
      { key: 'title', label: 'Title' },
      { key: 'type', label: 'Type' },
      { key: 'is_read', label: 'Read', render: (v) => (v ? '✓' : '—') },
      { key: 'createdAt', label: 'Date', render: (v, r) => new Date(v || r.created_at || '').toLocaleDateString() },
    ],
    searchFields: ['title', 'body', 'type'],
    deletable: true,
  },
  rooms: {
    key: 'rooms',
    path: 'chat-rooms',
    label: 'Chat Rooms',
    icon: '💬',
    columns: [
      { key: 'clientId', label: 'Client', render: (v, r) => cols.idShort(v || r.client_id) },
      { key: 'technicianId', label: 'Tech', render: (v, r) => <span className="kbd">{(v || r.technician_id || '').slice(0, 10)}</span> },
      { key: 'requestId', label: 'Request', render: (v, r) => cols.idShort(v || r.request_id) },
      { key: 'updatedAt', label: 'Updated', render: (v, r) => new Date(v || r.updated_at || '').toLocaleString() },
    ],
    searchFields: ['clientId', 'technicianId', 'requestId'],
    deletable: true,
  },
  audit: {
    key: 'audit',
    path: 'audit-logs',
    label: 'Audit Log',
    icon: '≡',
    columns: [
      { key: 'admin_email', label: 'Admin' },
      { key: 'action', label: 'Action' },
      { key: 'table_name', label: 'Table' },
      { key: 'record_id', label: 'Record', render: (v) => (v ? cols.idShort(v) : '—') },
      { key: 'created_at', label: 'Time', render: (v, r) => new Date(v || r.createdAt || '').toLocaleString() },
    ],
    searchFields: ['admin_email', 'action', 'table_name'],
    deletable: false,
  },
};
